project_id = "ddwlhgpugjyruzejggoz"

[functions.ai-chat]
verify_jwt = true

[functions.handle-anomaly-response]
verify_jwt = true

[functions.sync-taxonomies]
verify_jwt = false

[functions.sync-woo-products]
verify_jwt = false

[functions.update-woo-product]
verify_jwt = true

[functions.woocommerce-order-status]
verify_jwt = false

[functions.manage-taxonomy]
verify_jwt = false

[functions.bulk-sync-to-woo]
verify_jwt = true

[functions.woo-proxy]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.generate-webhook-secret]
verify_jwt = true
